### ISSUE TITLE
QC.Sty01 Python flake8 line length

### ISSUE THREAD

**Issue by BSchilperoort** [EOSC-synergy/sqaaas-reporting-plugins#62] opened 2023-02-27 11:41 UTC
I am not sure if this is the right repository to raise this issue, so feel free to move it if it belongs elsewhere.

We've used SQAaaS as for one of our [python packages](https://github.com/AI4S2S/lilio), and received a silver badge. The only thing blocking us from achieving gold however, is that we use a maximum line length of 88 characters instead of 79. This is also the default line length for the popular Python code formatter [Black](https://github.com/psf/black).

To quote [PEP 8](https://peps.python.org/pep-0008/#maximum-line-length):
> Some teams strongly prefer a longer line length. For code maintained exclusively or primarily by a team that can reach agreement on this issue, it is okay to increase the line length limit up to 99 characters

Is it possible to configure a different line length for the code style analyzer? I attempted to use a .flake8 configuration file but that one is ignored.

**Comment by orviz** [comment] 2023-02-27 14:06
Thanks @BSchilperoort for the feedback. Using a `.flake8` should work (same if using `tox.ini` or `setup.cfg` as described in the [docs](https://flake8.pycqa.org/en/latest/user/configuration.html#configuration-locations)).

Not sure if you are using the same github repo you referenced in the SQAaaS, but there I cannot see the `.flake8` file. Some common causes are due to multiple definitions of flake8 exceptions in the supported files, so they are not being read from the file one expects. Please paste here the repo and branch you are using if the issue persists for your specific case.

**Comment by orviz** [comment] 2023-02-27 14:49
Glad to hear the issue is solved, closing it

**Closed by orviz** 2023-02-27 14:49 UTC
